# Generated by Django 3.0.8 on 2020-08-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.TextField(default='None')),
                ('position', models.TextField()),
                ('mesh', models.TextField(null=True)),
            ],
            options={
                'db_table': 'Index',
            },
        ),
        migrations.CreateModel(
            name='MeshWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.TextField(default='None')),
                ('mesh', models.TextField()),
            ],
            options={
                'db_table': 'MeshWord',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField(default=0)),
                ('name', models.TextField(default='None')),
                ('title', models.TextField(default='')),
                ('text', models.TextField(default='None')),
                ('eof', models.TextField(null=True)),
                ('lemmas', models.TextField(null=True)),
            ],
            options={
                'db_table': 'Uploaded_file',
            },
        ),
    ]
